import { motion } from 'framer-motion'
import { useState, useEffect } from 'react'
import type { Dispatch, SetStateAction } from 'react'
import { runSimulationRequest } from '../../api/api'
import './SimulatorPreview.css'

interface SimulatorPreviewProps {
  selectedCode: string
  setSelectedCode: Dispatch<SetStateAction<string>>
}

export default function SimulatorPreview({ selectedCode, setSelectedCode }: SimulatorPreviewProps) {
  // Helper to extract entity name from VHDL code
  const extractEntityName = (source: string) => {
    const match = source.match(/entity\s+(\w+)\s+is/i)
    return match?.[1] || ''
  }
  const [code, setCode] = useState('')
  const [simulationStatus, setSimulationStatus] = useState<'idle' | 'running' | 'done'>('idle')
  const [simulationOutput, setSimulationOutput] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')

  // When selectedCode changes, update the editor
  useEffect(() => {
    if (selectedCode) {
      setCode(selectedCode)
      setSuccessMessage('Loaded design from gallery. Ready to simulate!')
    }
  }, [selectedCode])

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  }

  const runSimulation = async () => {
    if (!code.trim()) {
      setErrorMessage('Enter your VHDL code before running the simulation.')
      return
    }

    setSimulationStatus('running')
    setErrorMessage('')
    setSuccessMessage('')

    try {
      const response = await runSimulationRequest({
        code,
        language: 'VHDL',
        entityName: extractEntityName(code),
      })
      if (!response.data.success) {
        setSimulationStatus('idle')
        setErrorMessage(response.data.error || 'Simulation failed on the backend.')
        return
      }

      setSimulationOutput(response.data.output || 'Simulation complete')
      setSimulationStatus('done')
    } catch (error) {
      setSimulationStatus('idle')
      setErrorMessage('Simulation failed. Check backend connection.')
    }
  }

  const resetSimulation = () => {
    setSimulationStatus('idle')
    setSimulationOutput('')
    setErrorMessage('')
    setCode('')
    setSuccessMessage('')
  }

  const downloadVCD = () => {
    const vcdData = `# VCD generated by VHDL Simulator\n$timescale 1ns $end\n$var wire 1 ! a $end\n$var wire 1 \" b $end\n$var wire 1 # y $end\n$enddefinitions $end\n$dumpvars\n0!\n1\"\n0#\n$end\n`
    const blob = new Blob([vcdData], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'simulation.vcd'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const itemVariants = {
    hidden: { opacity: 0, x: -20 },
    visible: {
      opacity: 1,
      x: 0,
      transition: { duration: 0.6, ease: 'easeOut' },
    },
  }

  return (
    <section id="simulator" className="simulator-preview">
      <motion.div
        className="simulator-container"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.2 }}
        variants={containerVariants}
      >
        <div className="simulator-content">
          <motion.div variants={itemVariants}>
            <h2 className="section-title">
              Advanced <span className="title-highlight">Simulator</span>
            </h2>
          </motion.div>

          <motion.p variants={itemVariants} className="section-subtitle">
            Write, compile, and simulate VHDL code in real-time
          </motion.p>

          {/* Code Editor Preview */}
          <motion.div variants={itemVariants} className="editor-preview">
            <div className="editor-header">
              <span className="file-name">design.vhd</span>
              <div className="editor-buttons">
                <span>●●●</span>
              </div>
            </div>
            <div className="editor-body">
              <textarea
                className="code-editor"
                value={code}
                onChange={(e) => setCode(e.target.value)}
                placeholder={`-- Enter your VHDL code here\n-- Example:\n-- library IEEE;\n-- use IEEE.STD_LOGIC_1164.ALL;\n-- ...`}
                rows={14}
              />
            </div>
          </motion.div>

          {/* Simulation Controls */}
          <motion.div variants={itemVariants} className="simulator-controls">
            <button className="btn-simulate" onClick={runSimulation}>▶ Run Simulation</button>
            <button className="btn-secondary" onClick={resetSimulation}>Reset</button>
            <button className="btn-secondary" onClick={downloadVCD}>Download VCD</button>
          </motion.div>
          <motion.div variants={itemVariants} className="simulation-status">
            Status: {simulationStatus === 'idle' ? 'Ready' : simulationStatus === 'running' ? 'Running...' : 'Complete'}
          </motion.div>
          <motion.div variants={itemVariants} className="simulation-result">
            {successMessage && (
              <div className="simulation-success">{successMessage}</div>
            )}
            {errorMessage ? (
              <div className="simulation-error">{errorMessage}</div>
            ) : (
              simulationOutput && <pre className="simulation-output-text">{simulationOutput}</pre>
            )}
          </motion.div>

          {/* Waveform Preview */}
          <motion.div
            variants={itemVariants}
            className="waveform-preview"
            whileHover={{ boxShadow: '0 0 40px rgba(0, 255, 65, 0.4)' }}
          >
            <div className="waveform-header">Waveform Output</div>
            <div className="waveform-output">
              {simulationOutput || 'No waveform data yet. Run the simulation to see results.'}
            </div>
            <svg className="waveform-svg" viewBox="0 0 800 200">
              {/* Signal a */}
              <g>
                <text x="10" y="35" className="signal-label">Signal A</text>
                <path d="M 60 40 L 100 40 L 100 50 L 200 50 L 200 40 L 300 40 L 300 50 L 400 50" className="signal-path" />
              </g>

              {/* Signal b */}
              <g>
                <text x="10" y="95" className="signal-label">Signal B</text>
                <path d="M 60 100 L 150 100 L 150 110 L 250 110 L 250 100 L 350 100 L 350 110 L 400 110" className="signal-path" />
              </g>

              {/* Output */}
              <g>
                <text x="10" y="155" className="signal-label">Output Y</text>
                <path d="M 60 160 L 150 160 L 150 170 L 200 170 L 200 160 L 300 160 L 300 170 L 400 170" className="signal-path" />
              </g>

              {/* Grid */}
              <g className="grid-lines">
                {[...Array(8)].map((_, i) => (
                  <line key={i} x1={60 + i * 50} y1="20" x2={60 + i * 50} y2="180" stroke="rgba(0, 255, 65, 0.1)" strokeWidth="1" />
                ))}
              </g>
            </svg>
          </motion.div>
        </div>

        {/* Circuit Diagram Animation */}
        <motion.svg className="circuit-diagram" viewBox="0 0 300 300">
          <defs>
            <linearGradient id="circuitGradient" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor="rgba(0, 255, 65, 0.5)" />
              <stop offset="100%" stopColor="rgba(57, 255, 20, 0.3)" />
            </linearGradient>
          </defs>

          {/* Animated gates */}
          <motion.rect x="50" y="50" width="80" height="60" fill="none" stroke="url(#circuitGradient)" strokeWidth="2" rx="4" />
          <motion.circle cx="150" cy="80" r="20" fill="none" stroke="rgba(0, 255, 65, 0.5)" strokeWidth="2" animate={{ r: [20, 25, 20] }} transition={{ duration: 2, repeat: Infinity }} />
          <motion.line x1="30" y1="80" x2="50" y2="80" stroke="url(#circuitGradient)" strokeWidth="2" animate={{ strokeWidth: [2, 3, 2] }} transition={{ duration: 2, repeat: Infinity }} />
          <motion.line x1="130" y1="80" x2="150" y2="80" stroke="url(#circuitGradient)" strokeWidth="2" animate={{ strokeWidth: [2, 3, 2] }} transition={{ duration: 2, repeat: Infinity, delay: 0.3 }} />
        </motion.svg>
      </motion.div>
    </section>
  )
}
